platform :ios, '9.0'

target 'Merchant Cafe App' do

  use_frameworks!
pod 'Alamofire', '~> 4.7'
pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'Firebase/Storage'
pod 'Firebase/Firestore'
pod 'Firebase/Auth'
pod 'MBProgressHUD', '~> 1.1.0'
pod 'SideMenuSwift'
pod 'AlamofireImage', '~> 3.3'

end
