# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ITT Cafe' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ITT Cafe

pod 'Alamofire', '~> 4.7'
pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'Firebase/Storage'
pod 'Firebase/Firestore'

  target 'ITT CafeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ITT CafeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
